#!/usr/bin/env bash
#Bash script that loops from 1 to 10 and displays" bad luck" for the 4th loop iteration
count=1
while [ $count -ne 11 ]
do
    if [ $count -eq 4 ]; then
	echo "bad luck"
    elif [ $count -eq 8 ]; then
	echo "good luck"
    else
	echo "Best School"
    fi
    ((count++))
done
