#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes
hours=0
minutes=1
while [ $hours -ne 13 ]
do
    echo "Hour: $hours"
    ((hours++))
    while [ $minutes -ne 60 ]
    do
	echo $minutes
	((minutes++))
    done
    ((minutes = 1))
done
